//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailUser()
        {
            this.Users = new HashSet<User>();
            this.Relatives = new HashSet<Relative>();
        }
    
        public string CCCD { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public string PLACE_CCCD { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Ethnic { get; set; }
        public string SecondarySchool { get; set; }
        public string HealthInsuranceID { get; set; }
        public string AcademicAchievement { get; set; }
        public string FacultyCode { get; set; }
        public string FacultyName { get; set; }
        public string Majors { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relative> Relatives { get; set; }
    }
}
