//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Đồ_ÁnEntities : DbContext
    {
        public Đồ_ÁnEntities()
            : base("name=Đồ_ÁnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<DatabaseImageTable> DatabaseImageTables { get; set; }
        public virtual DbSet<DetailUser> DetailUsers { get; set; }
        public virtual DbSet<Notifycation> Notifycations { get; set; }
        public virtual DbSet<OTP> OTPs { get; set; }
        public virtual DbSet<Relative> Relatives { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
