//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Đồ_án.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Results = new HashSet<Result>();
            this.Classes = new HashSet<Class>();
            this.Notifycations = new HashSet<Notifycation>();
        }
    
        public string IdUser { get; set; }
        public string Passwd { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> IdOTP { get; set; }
        public Nullable<System.Guid> IdUserRole { get; set; }
        public Nullable<System.Guid> IdAvatar { get; set; }
        public string CCCD { get; set; }
    
        public virtual DatabaseImageTable DatabaseImageTable { get; set; }
        public virtual DetailUser DetailUser { get; set; }
        public virtual OTP OTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifycation> Notifycations { get; set; }
    }
}
